[tool.poetry]
name = "nautobot-secrets-reader"
version = "0.9.2"
description = "Retrieve the Secret-Values of Nautobot Secrets-Groups from the Secret-Server-Provider."
authors = ["Josef Fuchs <j053ff0x@gmail.com>"]
homepage = "https://github.com/jifox/secret-server-reader.git"
keywords = ["nautobot", "delinea", "thycotic", "secret", "secret-server", "secrets", "secrets-provider", "secrets-group", "secrets-reader"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.9,<4.0.0"
python-dotenv = "*"
types-requests = "*"
requests = "*"
pynautobot = "*"
python-tss-sdk = "*"

[tool.poetry.dev-dependencies]
black = "*"
pylama = "*"
pytest = "*"
mypy = "*"
jupyterlab = "*"
PyYAML = "*"
"ruamel.yaml" = "*"
ipykernel = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
